# Generated by Django 2.1.2 on 2018-12-04 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogistepsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'LogiSteps User',
                'verbose_name_plural': 'LogiSteps Users',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_left', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Logisteps Smart Shoe',
                'verbose_name_plural': 'Logisteps Smart Shoes',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logisteps.Location')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisteps.Shoe')),
            ],
            options={
                'verbose_name': 'Logisteps Step',
                'verbose_name_plural': 'Logisteps Steps',
            },
        ),
        migrations.AddField(
            model_name='logistepsuser',
            name='left_shoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_left_shoe', to='logisteps.Shoe'),
        ),
        migrations.AddField(
            model_name='logistepsuser',
            name='right_shoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_right_shoe', to='logisteps.Shoe'),
        ),
        migrations.AddField(
            model_name='logistepsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
