# Generated by Django 2.1.2 on 2018-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='sensorreading',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='location',
            field=models.CharField(choices=[('T', 'top'), ('B', 'bottom')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='foot',
            field=models.CharField(choices=[('R', 'right'), ('L', 'left')], max_length=1),
        ),
    ]
