# Generated by Django 2.1.2 on 2018-12-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0002_auto_20181212_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='shoe',
        ),
        migrations.AddField(
            model_name='step',
            name='sensor_reading',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='logisteps.SensorReading'),
            preserve_default=False,
        ),
    ]
