# Generated by Django 2.1.2 on 2018-12-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0003_auto_20181212_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistepsuser',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistepsuser',
            name='step_goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistepsuser',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
