# Generated by Django 2.1.2 on 2019-01-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0004_auto_20181216_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='date',
        ),
        migrations.RemoveField(
            model_name='step',
            name='time',
        ),
        migrations.AddField(
            model_name='step',
            name='datetime',
            field=models.DateTimeField(default='1996-10-22T12:12:12Z'),
            preserve_default=False,
        ),
    ]
