# Generated by Django 2.1.2 on 2019-01-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0005_auto_20190106_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='logisteps.LogistepsUser'),
            preserve_default=False,
        ),
    ]
