# Generated by Django 2.1.7 on 2019-03-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisteps', '0006_step_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='sensor_reading',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='step',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='logisteps.Step'),
            preserve_default=False,
        ),
    ]
